version: '3'
services:
  db:
    image: postgres:15.3-alpine3.18
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
